version: "3.8"

services:
  discord-bot:
    container_name: discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
      - bot-logs:/app/logs
    environment:
      - TZ=UTC
      # Email server configuration
      - imap_server
      - imap_user
      - imap_password
      - imap_port
      - imap_ssl
      # OpenAI API key for email summarization
      - openai_api_key
      # Discord bot configuration
      - discord_token
      - discord_channel_id
      # Comma-separated list of whitelisted email addresses to monitor
      - whitelisted_email_addresses
      # Logging configuration
      - log_level
      - log_concise
      - log_to_file
      - log_dir
    healthcheck:
      test: ["CMD", "python", "./src/utils/healthcheck.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  bot-logs: